### ISSUE TITLE
Unifi Protect Container doesn't start

### ISSUE THREAD

**Issue by icaroscherma** [markdegrootnl/dockerfiles#1]
Docker log output:
```
database exists
Error: Config owner (postgres:101) and data owner (root:0) do not match, and config owner is not root
```

Then I deleted and re-created the container and now the logs it's like:

![image](https://user-images.githubusercontent.com/42467/90322490-ba35a900-df09-11ea-9f35-77285d1a492c.png)

---

Is it related to user permissions on the volumes?

---

**Edit:** I got it working if I don't link the postgres database to a volume :/

---

**Edit2:**
To fix my main issue: Instead of linking the volume to `/var/lib/postgresql/10/main`, just link to `/var/lib/postgresql` and the permissions will be fixed on the first start.

Other issue that will show up later if you just use the port mapping is that the docker need to have external internet access, (tip from https://github.com/iamjamestl/docker-unifi-protect ), so maybe it's better to just use a bridge mode on the container.
So if you get a blue screen saying something like `connecting to your nvr...`, it's the port mapping issue.

**Comment by markdegrootnl** [comment]
Hi @icaroscherma, 

Good to hear you've managed to solve the issue. 

Also thanks for the bridge/port-forward information. We've had some users stuck at `connecting to your nvr...` while others never had the issue. Good to know that it might be related to the external internet access.
