### ISSUE TITLE
unifi protect x86 update

### ISSUE THREAD

**Issue by bjekel** [markdegrootnl/dockerfiles#2]
Hi, I noticed that the docker image for unifi protect arm64 got an update. Will x86 also be getting an update? (If it's available for x86)

**Comment by markdegrootnl** [comment]
Hi @bartjekel 

Unfortunately UniFi stopped publishing x86 packages. If anyone can get them, I'd love to make an update but for now it's ARM64 only.

**Comment by bjekel** [comment]
Ok, that's too bad, hopefully they will publish it again. Then I will try to run it on my raspberry pi or maybe I can find some other way to run it on x86.

Thanks for the awesome work on these docker images! :-D
