### ISSUE TITLE
Any future Protect releases to be made available?

### ISSUE THREAD

**Issue by markusd1984** [markdegrootnl/dockerfiles#7]
Thanks for the hard work, I managed [to set it up with this tutorial ](https://www.youtube.com/watch?v=a-VjH5M-8O0&t=200s) and try out the interface, Nice!

Any chance / plans to get newer releases made available? e.g. last one from dec [v1.3.35 UNVR](https://community.ui.com/releases/UniFi-Protect-NVR-Firmware-1-3-35/543d458f-7082-40c0-bf52-a091bc993ea4) or [2.0.24 CKGen2+](https://community.ui.com/releases/UniFi-Cloud-Key-Firmware-2-0-24/b6684f1e-8542-4660-bc0b-74e0634448e8)?

I understand that Ubiquiti could throw a spanner in the way, hoping they won't or even change their mind to support it, especially for home users to help decide purchasing their cameras to use with their software, as an easy and attractive migration coming from using Google/Nest!

**Comment by markdegrootnl** [comment]
For x86 1.13.3 is the latest version available. After this UniFi stopped publishing x86 binaries. 

arm64 is currently at 1.15.0 and will be updated to the latest version when I find the time.
